
project_id = "gbztiauhydgyzvskqtrk"

[api]
# Port to use for the API URL
port = 54321
# Set an API hostname, either CNAME or part of Fly.io or Render
hostname = "localhost"

[dev]
url = "postgres://postgres:postgres@localhost:54322/postgres"

[[functions]]
name = "send-email"
verify_jwt = false

[[functions]]
name = "check-subscription"
verify_jwt = false

[[functions]]
name = "analyze-project"
verify_jwt = false

[[functions]]
name = "create-checkout"
verify_jwt = false

[[functions]]
name = "stripe-webhook"
verify_jwt = false

[[functions]]
name = "cancel-subscription"
verify_jwt = false

[[functions]]
name = "create-portal-session"
verify_jwt = false
