
project_id = "gbztiauhydgyzvskqtrk"

[functions.send-email]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.analyze-project]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.generate-insurance-templates]
verify_jwt = false

[functions.generate-tax-form-info]
verify_jwt = false

[functions.generate-turbotax-instructions]
verify_jwt = false
