
project_id = "gbztiauhydgyzvskqtrk"

[functions.send-email]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.analyze-project]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false
